[package]
name = "quintet"
version = "0.2.0"
authors = ["yubessy <yubessy0@gmail.com>"]
description = "Renju library with wasm-pack"
license = "MIT"
edition = "2018"
repository = "https://github.com/renju-note/quintet"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O3", "--enable-mutable-globals"]
